<a href="https://colab.research.google.com/github/thiyyagurapadmavathi/python-tutorials/blob/main/python_day4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
n=int(input("entaer a value:"))
for i in range(2,n):
    if n%i==0:
       print(" not prime")
       break
else:
    print("prime")

entaer a value:10
 not prime


In [ ]:
n=int(input("entaer a value:"))
for j in range(1,n+1):
    for i in range(2,j):
        if j%i==0:
           break
    else:
        print(j)   
       

entaer a value:10
1
2
3
5
7


ARRAY IN PYTHON

In [ ]:
from array import *
values=array('i',[2,3,5,1,6])
print(values)

array('i', [2, 3, 5, 1, 6])


In [ ]:
values=array('i',[2,3,-5,1,6])
print(values)

array('i', [2, 3, -5, 1, 6])


In [ ]:
values=array('i',[2,3,5.2,'padma',6])  ##because array is of same type
print(values)

TypeError: ignored

In [ ]:
values=array('i',[2,3,5,1,6])
values.reverse()
print(values)

array('i', [6, 1, 5, 3, 2])


In [ ]:
values=array([2,3,-5,1,6])
print(values)

[ 2  3 -5  1  6]


In [ ]:
values=array('I',[2,3,-5,-1,6]) ## 'I' for unsingned print(values)

OverflowError: ignored

In [ ]:
values=array('i',[2,3,5,1,6])
print(values[0])

2


In [ ]:
values=array('i',[2,3,5,1,6])
print(values[0:])


array('i', [2, 3, 5, 1, 6])


In [ ]:
values=array('i',[2,3,5,1,6])
for i in values :
     print(i)

2
3
5
1
6


In [ ]:
values=array('i',[2,3,5,1,6])
newarray=array(values.typecode,(a*a for a in values))
for i in newarray: ##while i<len(newarray):
    print(i)

4
9
25
1
36


In [ ]:
arr=array('i',[])
n=int(input("enter the lenth of the array:"))
for i in range(n):
    x=int(input("enter array element:"))
    arr.append(x)
print(arr)

enter the lenth of the array:5
enter array element:23
enter array element:10
enter array element:45
enter array element:12
enter array element:24
array('i', [23, 10, 45, 12, 24])


In [ ]:
arr=array('i',[])
n=int(input("enter the lenth of the array:"))
for i in range(n):
    x=int(input("enter array element:"))
    arr.append(x)
print(arr)
val=int(input("enter avalue to search:"))
k=0
for e in arr:
    if e==val:
       print(k)
       break
    k+=1
print(arr.index(val))


enter the lenth of the array:4
enter array element:1
enter array element:2
enter array element:3
enter array element:4
array('i', [1, 2, 3, 4])
enter avalue to search:4
3
3


In [ ]:
arr=array('i',[1,2,3,4],[5,6,7,8])
print(arr)

TypeError: ignored

In [ ]:
pip install numpy

In [ ]:
 import numpy
arr=array([1,2,3,4],[5,6,7,8])
print(arr)

TypeError: ignored

In [ ]:
arr=array([1,2,3,4,5.0])
#print(arr.dtype)
print(arr)

[1. 2. 3. 4. 5.]


In [ ]:
arr=array([1,2,3,4,5.0],int)
#print(arr.dtype)
print(arr)

[1 2 3 4 5]


In [ ]:
arr=linspace(0,16,15)
print(arr)

[ 0.          1.14285714  2.28571429  3.42857143  4.57142857  5.71428571
  6.85714286  8.          9.14285714 10.28571429 11.42857143 12.57142857
 13.71428571 14.85714286 16.        ]


In [ ]:
arr=arange(1,15,2)
print(arr)

[ 1  3  5  7  9 11 13]


In [ ]:
arr=logspace(1,40,5)
print(arr)

[1.00000000e+01 5.62341325e+10 3.16227766e+20 1.77827941e+30
 1.00000000e+40]


In [ ]:
##arr=zeros(5) 
arr=ones(5,int)
print(arr)

[1 1 1 1 1]


In [ ]:
arr=array([1,2,3,4,5])
arr1=array([6,7,8,9,10])
print(sin(arr))
print(sqrt(arr))
print(log(arr))
print(sum(arr))
print(max(arr))
print(min(arr))
print(arr+arr1)
print(concatenate([arr,arr1]))

[ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427]
[1.         1.41421356 1.73205081 2.         2.23606798]
[0.         0.69314718 1.09861229 1.38629436 1.60943791]
15
5
1
[ 7  9 11 13 15]
[ 1  2  3  4  5  6  7  8  9 10]


In [ ]:
arr=array([1,2,3,4,5]) 
arr=arr1.view() ##creat an array af diffrent location 
print(arr)
print(arr1) 
print(id(arr)) 
print(id(arr1))



[ 6  7  8  9 10]
[ 6  7  8  9 10]
139946858410272
139946858410752


In [ ]:
arr=array([1,2,3,4,5]) 
arr=arr1.view() ##creat an array af diffrent location
arr1[1]=7 ## shallow copy
print(arr)
print(arr1) 
print(id(arr)) 
print(id(arr1))



[ 6  7  8  9 10]
[ 6  7  8  9 10]
139946858210928
139946858410752


In [67]:
arr=array([1,2,3,4,5]) 
arr=arr1.copy()#creat an array af diffrent location 
arr1[1]=7
print(arr)
print(arr1) 
print(id(arr)) 
print(id(arr1))

[ 6  7  8  9 10]
[ 6  7  8  9 10]
139946858717056
139946858410752
